server:
  port: 8083

spring:
  application:
    name: schedule-query
  main:
    allow-bean-definition-overriding: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/schedule?createDatabaseIfNotExist=true
    username: root
    password: pwd
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
  eventhandling:
    processors:
      schedule:
        mode: tracking